### ISSUE TITLE
JVMCI for the x86 target

### ISSUE THREAD

**Issue by gwipplinger** [gwipplinger/labs-openjdk-11#1]
Currently the module jdk.internal.vm.ci provides the jvmci implementation for
* amd64
* aarch64
* sparc

In a first step a 32 bit variant for the intel architecture should be added. The name of the target architecture is "x86" or "i386".

**Comment by gwipplinger** [comment]
To use the new jvm you have to delete the directory oracle/graal/substratevm/svmbuild. A build with mx native-image --version results in 
```
Exception during JVMCI compiler initialization
org.graalvm.compiler.debug.GraalError: No backend available for host architecture "i386"
	at org.graalvm.compiler.hotspot.HotSpotGraalRuntime.<init>(jdk.internal.vm.compiler/HotSpotGraalRuntime.java:206)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(jdk.internal.vm.compiler/HotSpotGraalCompilerFactory.java:179)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(jdk.internal.vm.compiler/HotSpotGraalCompilerFactory.java:157)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(jdk.internal.vm.compiler/HotSpotGraalCompilerFactory.java:53)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getCompiler(jdk.internal.vm.ci@11.0.11-internal/HotSpotJVMCIRuntime.java:733)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(jdk.internal.vm.ci@11.0.11-internal/HotSpotJVMCIRuntime.java:807)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (jvmciRuntime.cpp:1223), pid=7533, tid=7553
#  fatal error: Fatal exception in JVMCI: Exception during JVMCI compiler initialization
#
# JRE version: OpenJDK Runtime Environment GraalVM 21.2.0-dev (11.0.11) (build 11.0.11-internal+0-adhoc.gerhard.labs-openjdk-11)
# Java VM: OpenJDK Server VM GraalVM 21.2.0-dev (11.0.11-internal+0-adhoc.gerhard.labs-openjdk-11, mixed mode, sharing, tiered, jvmci, jvmci compiler, g1 gc, linux-x86)
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/gerhard/github/oracle/graal/substratevm/core.7533)
#
# An error report file with more information is saved as:
# /home/gerhard/github/oracle/graal/substratevm/hs_err_pid7533.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
```

So the next step would be to add the i386 target to e.g. the llvm backend.

**Comment by gwipplinger** [comment]
Using the llvm backend:
```
oracle/graal/substratevm$ mx native-image --verbose -H:CompilerBackend=llvm  Hello
```
results in
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0xf78465e1, pid=8297, tid=8317
#
# JRE version: OpenJDK Runtime Environment GraalVM 21.2.0-dev (11.0.11) (build 11.0.11-internal+0-adhoc.gerhard.labs-openjdk-11)
# Java VM: OpenJDK Server VM GraalVM 21.2.0-dev (11.0.11-internal+0-adhoc.gerhard.labs-openjdk-11, mixed mode, sharing, tiered, jvmci, jvmci compiler, g1 gc, linux-x86)
# Problematic frame:
# V  [libjvm.so+0xb9a5e1]  Symbol::as_C_string() const+0x11
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/gerhard/github/oracle/graal/substratevm/core.8297)
#
# An error report file with more information is saved as:
# /home/gerhard/github/oracle/graal/substratevm/hs_err_pid8297.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#

```
For better debugging support a debug variant of the jdk could be used:
```
graalvm/labs-openjdk-11$ bash configure --with-target-bits=32 --enable-debug
...
graalvm/labs-openjdk-11$ make CONF=debug product-bundles static-libs-bundles
...
```
The failing build:
```
.../graalvm/labs-openjdk-11/src/hotspot/cpu/x86/templateInterpreterGenerator_x86.cpp: In member function ‘u_char* TemplateInterpreterGenerator::generate_deopt_entry_for(TosState, int, address)’:
/home/gerhard/github/graalvm/labs-openjdk-11/src/hotspot/cpu/x86/templateInterpreterGenerator_x86.cpp:276:23: error: ‘r15_thread’ was not declared in this scope
       __ cmpb(Address(r15_thread, JavaThread::pending_monitorenter_offset()), 0);
...
```
can by bypassed with a workaround - graalvm/labs-openjdk-11/src/hotspot/cpu/x86/templateInterpreterGenerator_x86.cpp:276
```
#ifdef ASSERT
#ifdef _LP64
    if (EnableJVMCI) {
      Label L;
      __ cmpb(Address(r15_thread, JavaThread::pending_monitorenter_offset()), 0);
      __ jccb(Assembler::zero, L);
      __ stop("unexpected pending monitor in deopt entry");
      __ bind(L);
    }
#endif
#endif

```

If this debug version of the jdk is used the mx build (with llvm backend) produces:
```
# To suppress the following error report, specify this argument
# after -XX: or in .hotspotrc:  SuppressErrorAt=/jvmciCompilerToVMInit.cpp:397
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (/home/gerhard/github/graalvm/labs-openjdk-11/src/hotspot/share/jvmci/jvmciCompilerToVMInit.cpp:397), pid=11605, tid=11625
#  assert(flag != __null) failed: No such flag named ObjectAlignmentInBytes
#
# JRE version: OpenJDK Runtime Environment GraalVM 21.2.0-dev (11.0.11) (fastdebug build 11.0.11-internal+0-adhoc.gerhard.labs-openjdk-11)
# Java VM: OpenJDK Server VM GraalVM 21.2.0-dev (fastdebug 11.0.11-internal+0-adhoc.gerhard.labs-openjdk-11, mixed mode, sharing, tiered, jvmci, jvmci compiler, g1 gc, linux-x86)
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/gerhard/github/oracle/graal/substratevm/core.11605)
#
# An error report file with more information is saved as:
# /home/gerhard/github/oracle/graal/substratevm/hs_err_pid11605.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#

```

**Comment by gwipplinger** [comment]
```
$ mx -p ~/github/oracle/graal/substratevm native-image --verbose -H:CompilerBackend=llvm Hello
Unsafe address size: 4
java.lang.IllegalArgumentException: Signature must start with a '(': min
	at jdk.vm.ci.hotspot.HotSpotSignature.<init>(jdk.internal.vm.ci@11.0.11-internal/HotSpotSignature.java:68)
	at jdk.vm.ci.hotspot.HotSpotConstantPool.lookupSignature(jdk.internal.vm.ci@11.0.11-internal/HotSpotConstantPool.java:567)
	at jdk.vm.ci.hotspot.HotSpotResolvedJavaMethodImpl.<init>(jdk.internal.vm.ci@11.0.11-internal/HotSpotResolvedJavaMethodImpl.java:139)
	at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.createMethod(jdk.internal.vm.ci@11.0.11-internal/HotSpotResolvedObjectTypeImpl.java:544)
	at jdk.vm.ci.hotspot.HotSpotResolvedJavaMethodImpl.fromMetaspace(jdk.internal.vm.ci@11.0.11-internal/HotSpotResolvedJavaMethodImpl.java:116)
Unsafe address size: 4
java.lang.IllegalArgumentException: Signature must start with a '(': fillNull
	at jdk.vm.ci.hotspot.HotSpotSignature.<init>(jdk.internal.vm.ci@11.0.11-internal/HotSpotSignature.java:68)
	at jdk.vm.ci.hotspot.HotSpotConstantPool.lookupSignature(jdk.internal.vm.ci@11.0.11-internal/HotSpotConstantPool.java:567)
	at jdk.vm.ci.hotspot.HotSpotResolvedJavaMethodImpl.<init>(jdk.internal.vm.ci@11.0.11-internal/HotSpotResolvedJavaMethodImpl.java:139)
	at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.createMethod(jdk.internal.vm.ci@11.0.11-internal/HotSpotResolvedObjectTypeImpl.java:544)
	at jdk.vm.ci.hotspot.HotSpotResolvedJavaMethodImpl.fromMetaspace(jdk.internal.vm.ci@11.0.11-internal/HotSpotResolvedJavaMethodImpl.java:116)
Unsafe address size: 4
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0xf757971e, pid=16830, tid=16850Unsafe address size: 4
#
# JRE version: OpenJDK Runtime Environment GraalVM 21.2.0-dev (11.0.11) (fastdebug build 11.0.11-internal+0-adhoc.ubuntu.labs-openjdk-11)
# Java VM: OpenJDK Server VM GraalVM 21.2.0-dev (fastdebug 11.0.11-internal+0-adhoc.ubuntu.labs-openjdk-11, mixed mode, sharing, tiered, jvmci, jvmci compiler, g1 gc, linux-x86)
# Problematic frame:
# V  [libjvm.so+0x15c071e]
java.lang.IllegalArgumentException: Signature must start with a '(': toLowerCase
	at jdk.vm.ci.hotspot.HotSpotSignature.<init>(jdk.internal.vm.ci@11.0.11-internal/HotSpotSignature.java:68)
	at jdk.vm.ci.hotspot.HotSpotConstantPool.lookupSignature(jdk.internal.vm.ci@11.0.11-internal/HotSpotConstantPool.java:567)
	at jdk.vm.ci.hotspot.HotSpotResolvedJavaMethodImpl.<init>(jdk.internal.vm.ci@11.0.11-internal/HotSpotResolvedJavaMethodImpl.java:139)
	at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.createMethod(jdk.internal.vm.ci@11.0.11-internal/HotSpotResolvedObjectTypeImpl.java:544)
	at jdk.vm.ci.hotspot.HotSpotResolvedJavaMethodImpl.fromMetaspace(jdk.internal.vm.ci@11.0.11-internal/HotSpotResolvedJavaMethodImpl.java:116)
Unsafe address size: 4
java.lang.IllegalArgumentException: Signature must start with a '(': toLowerCaseCharArray
	at jdk.vm.ci.hotspot.HotSpotSignature.<init>(jdk.internal.vm.ci@11.0.11-internal/HotSpotSignature.java:68)
	at jdk.vm.ci.hotspot.HotSpotConstantPool.lookupSignature(jdk.internal.vm.ci@11.0.11-internal/HotSpotConstantPool.java:567)
	at jdk.vm.ci.hotspot.HotSpotResolvedJavaMethodImpl.<init>(jdk.internal.vm.ci@11.0.11-internal/HotSpotResolvedJavaMethodImpl.java:139)
	at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.createMethod(jdk.internal.vm.ci@11.0.11-internal/HotSpotResolvedObjectTypeImpl.java:544)
	at jdk.vm.ci.hotspot.HotSpotResolvedJavaMethodImpl.fromMetaspace(jdk.internal.vm.ci@11.0.11-internal/HotSpotResolvedJavaMethodImpl.java:116)
  Symbol::as_C_string() const+0xe
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/ubuntu/Test/hs_err_pid16830.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Current thread is 16850
Dumping core ...
```

**Comment by gwipplinger** [comment]
The commit 185b099 solves the reading of the constant pool. the next step is probably to solve the following problem:
```
Exception during JVMCI compiler initialization
org.graalvm.compiler.debug.GraalError: No backend available for host architecture "i386"
	at org.graalvm.compiler.hotspot.HotSpotGraalRuntime.<init>(jdk.internal.vm.compiler/HotSpotGraalRuntime.java:206)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(jdk.internal.vm.compiler/HotSpotGraalCompilerFactory.java:179)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(jdk.internal.vm.compiler/HotSpotGraalCompilerFactory.java:157)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(jdk.internal.vm.compiler/HotSpotGraalCompilerFactory.java:53)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getCompiler(jdk.internal.vm.ci@11.0.11-internal/HotSpotJVMCIRuntime.java:733)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(jdk.internal.vm.ci@11.0.11-internal/HotSpotJVMCIRuntime.java:807)
```

**Comment by tofische** [comment]
Following patch switches of the usage of the JVMCI for the SubstrateVM itself:

```
--- a/substratevm/mx.substratevm/mx_substratevm.py
+++ b/substratevm/mx.substratevm/mx_substratevm.py
@@ -903,7 +903,7 @@ def _native_image_launcher_extra_jvm_args():
     res = []
     jdk = mx.get_jdk(tag='default')
     if not mx_sdk_vm.jdk_enables_jvmci_by_default(jdk):
-        res.extend(['-XX:+UnlockExperimentalVMOptions', '-XX:+EnableJVMCI'])
+        res.extend(['-XX:+UnlockExperimentalVMOptions', '-XX:+EnableJVMCI', '-XX:-UseJVMCICompiler'])
     return res

```

**Comment by tofische** [comment]
Now, a 32 bit version of the svm clibraries is necessary. This can be achieved by adding a linux-i386 combination to the build suite substratevm/mx.substratevm/suite.py equal to linux-amd64 with added option "-m32".

The resulting clibraries will be built in `~/github/oracle/graal/sdk/mxbuild/linux-amd64/GRAALVM_52AFF0064F_JAVA11/graalvm-52aff0064f-java11-21.2.0-dev/lib/svm/clibraries/linux-amd64` which is a wrong path, therefore in the parent directory a symbolic link from `linux-i386` to `linux-amd64` is added.

**Comment by tofische** [comment]
```
$ mx -p ~/github/oracle/graal/substratevm native-image --verbose -H:CompilerBackend=llvm Hello
Invalid maximum heap size: -Xmx13454809496
The specified size exceeds the maximum representable size.
```

As a workaround the constructed command line has been directly entered with the option -Xmx2G.

**Comment by tofische** [comment]
```
Exception in thread "main" com.oracle.svm.core.util.UserError$UserException: Platform specified as linux-i386 isn't supported.
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.NativeImageGenerator.loadPlatform(NativeImageGenerator.java:351)
	at com.oracle.svm.hosted.NativeImageGenerator.getTargetPlatform(NativeImageGenerator.java:382)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:177)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:578)
```

**Comment by tofische** [comment]
Add platform i386 to sdk:
```
sdk/src/org.graalvm.nativeimage/src/META-INF/services/org.graalvm.nativeimage.Platform
sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/Platform.java
```

and rebuild the SDK (don't forget to delete mxbuild first).

```
Exception in thread "main" org.graalvm.compiler.debug.GraalError: No backend available for host architecture "i386"
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalRuntime.<init>(HotSpotGraalRuntime.java:206)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:179)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:157)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:53)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getCompiler(HotSpotJVMCIRuntime.java:733)
	at com.oracle.svm.hosted.c.GraalAccess.getGraalCapability(GraalAccess.java:50)
	at com.oracle.svm.hosted.c.GraalAccess.getOriginalTarget(GraalAccess.java:38)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.isValidArchitecture(NativeImageGeneratorRunner.java:235)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.verifyValidJavaVersionAndPlatform(NativeImageGeneratorRunner.java:448)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:246)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:540)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:120)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:578)
```

**Comment by gwipplinger** [comment]
The following bug was caused by a jlong/long conversion problem, which is fixed by commit f5531f4
```
Caused by: java.lang.NullPointerException
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.CompilerToVM.readFieldValue(Native Method)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotConstantReflectionProvider.readFieldValue(HotSpotConstantReflectionProvider.java:169)
	at com.oracle.svm.hosted.c.info.InfoTreeBuilder.createEnumConstantInfo(InfoTreeBuilder.java:667)
	at com.oracle.svm.hosted.c.info.InfoTreeBuilder.createEnumInfo(InfoTreeBuilder.java:651)
	at com.oracle.svm.hosted.c.info.InfoTreeBuilder.construct(InfoTreeBuilder.java:122)
	at com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:88)
	at com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:552)
```
